import { Product } from "./product";

export var ListSingleProductLeft = [
        new Product(1,
            "Samsung Galaxy s5-2015",
            "700.00",
            "100.00",
            "product-1.jpg"),

        new Product(2,
            "Nokia Lumia 1320",
            "899.00",
            "999.00",
            "product-2.jpg"),

        new Product(3,
            "LG Leon 2015",
            "400.00",
            "425.00",
            "product-3.jpg"),

        new Product(4,
            "Sony microsoft",
            "200.00",
            "",
            "product-4.jpg"),

        new Product(5,
            "iPhone 6",
            "1200.00",
            "1355.00",
            "product-5.jpg"),
        new Product(6,
            "iPhone 9",
            "1200.00",
            "1355.00",
            "product-5.jpg"),

        new Product(7,
            "Samsung gallaxy note 4",
            "900.00",
            "",
            "product-6.jpg"),

        new Product(8,
            "Nokia X1",
            "100.00",
            "200.00",
            "product-1.jpg"),
        new Product(9,
            "Iphone 7s Plus",
            "300.00",
            "",
            "product-5.jpg"),
        new Product(10,
            "Iphone 8s",
            "1450.00",
            "",
            "product-4.jpg"),
    ];